### ISSUE TITLE
Problem using VS2013 compiler on cygwin

### ISSUE THREAD

**Issue by byon** [jpakkane/meson#111]
I tried out the simple C-tutorial using VS2013 compiler with Ninja backend and running the commands on cygwin. I can get compilation to work. However, link command seems to get garbage characters into the command.

```
$ CC=cl CXX=cl /cygdrive/d/Utilities/ChocolateyPackages/python/python $(cygpath.exe -w /cygdrive/d/Utilities/meson/meson.py) build/
The Meson build system
Version: 0.24.0-research
Source dir: C:\Users\byon\Documents\src\experiments\meson
Build dir: C:\Users\byon\Documents\src\experiments\meson\build
Build type: native build
Project name: tutorial
Native c compiler: cl (msvc 18.00.31101)
Build targets in project: 1
$ ninja -v -C build/
ninja: Entering directory `build/'
[1/2] cl "/nologo" "/showIncludes" "/FS" "/W3" "/MDd" "/Zi" "/Ob0" "/Od" "/RTC1" "-Idemo.dir" "-I.." "-I."  /Fodemo.dir\main.c.obj /c ..\main.c
[2/2] cmd /c link   /OUT:demo.exe demo.dir\main.c.obj "/nologo"
FAILED: cmd /c link   /OUT:demo.exe demo.dir\main.c.obj "/nologo"
link: extra operand ÔÇÿ/nologoÔÇÖ
Try 'link --help' for more information.
ninja: build stopped: subcommand failed.
```

Note: I needed to explicitly use Windows python (as opposed to cygwin version) to get the command quoted properly. I assume the windows compilation commands require double quotes, and cygwin commands require single quotes. This is not particularly convenient, but ok as I can work around it.

Some additional information:

I can get the build to work on cygwin, if I use cygwin versions of python and gcc:
```
$ CC=gcc CXX=gcc meson.py build/; ninja -C build/
The Meson build system
Version: 0.24.0-research
Source dir: /cygdrive/c/Users/byon/Documents/src/experiments/meson
Build dir: /cygdrive/c/Users/byon/Documents/src/experiments/meson/build
Build type: native build
Project name: tutorial
Native c compiler: gcc (gcc 4.9.2)
Build targets in project: 1
ninja: Entering directory `build/'
[2/2] Linking target demo
```

And I can get the build to work, if using windows python and cl.exe on windows command line:
```
> set CC=cl
> set GCC=cl
> d:\Utilities\ChocolateyPackages\python\python.exe d:\Utilities\meson\meson.py build
The Meson build system
Version: 0.24.0-research
Source dir: c:\Users\byon\Documents\src\experiments\meson
Build dir: c:\Users\byon\Documents\src\experiments\meson\build
Build type: native build
Project name: tutorial
Native c compiler: cl (msvc 18.00.31101)
Build targets in project: 1
> ninja -v -C build
ninja: Entering directory `build'
[1/2] cl "/nologo" "/showIncludes" "/FS" "/W3" "/MDd" "/Zi" "/Ob0" "/Od" "/RTC1" "-Idemo.dir" "-I.." "-I."  /Fodemo.dir\main.c.obj /c ..\main.c
[2/2] cmd /c link   /OUT:demo.exe demo.dir\main.c.obj "/nologo"
> ninja -v -C build
ninja: Entering directory `build'
[1/1] cmd /c link   /OUT:demo.exe demo.dir\main.c.obj "/nologo"
>
```

I am using python 3.4.1, ninja 1.5.3, and meson straight from Github (latest commit 28476aa7).

**Comment by jpakkane** [comment]
This seems like an encoding bug somewhere in the chain. Could you please provide some more information:

- which version of Windows this si
- which language/locale are you using
- if you open the Ninja file with notepad, are the quotes around the link command the correct quote marks or ÔÇÿ
- are you running Meson from the VS command prompt rather than the regular one

**Comment by byon** [comment]
Thanks for a very swift response. :)

Here's the information:
- Windows version is 8.1
- Language / locale:
  - Cygwin environment variables has LANG=en_GB.UTF-8 and LOCALE is not set at all.
  - In OS level settings language is English (UK), locale is Finnish.
  - Note that I have not played too much with locale settings in the past, so I might have checked incorrect places. Please let me know, if you want me to specifically check something.
- In the failing case I am running meson from cygwin bash using ConEmu console emulator. I set the necessary VS environment variables by running vsvars32.bat before starting bash.
- Running from VS command prompt does work (I had an example in the original message)
- build.ninja seems to have the quotes ok:
```
build demo.exe: c_LINKER demo.dir\main.c.obj
 LINK_ARGS = "/nologo"
 aliasing =
```

I checked if there were any differences in build.ninja when generated from cygwin and from VS prompt. All I could see were that the end of lines were different, and that hard drive identifiers had different case (i.e. d: instead of D:).

**Comment by jpakkane** [comment]
The actual quoting issue is still a mystery but I tweaked the link command so this no longer happens. Can you test again please?

**Comment by byon** [comment]
It did no difference, but I happened to stumble on a clue that will likely lead into the actual solution. I just noticed that link.exe is pointing to cygwin's /usr/bin/link and not Visual Studio linker. That obviously cannot work.

So, this looks like a problem in my environment, rather than meson. Sorry about the hassle. :/
