### ISSUE TITLE
Feature request: support for wxWidgets library and wx-config

### ISSUE THREAD

**Issue by Phitherek** [jpakkane/meson#27]
I am creating a project in wxWidgets and I want to use Meson to compile it. wxWidgets uses its own "*-config" tool called wx-config (or sometimes wx-config-versionnumber for older library version, but it appears to be handled by newer wx-config as well with the --version=... option). It is slightly extended custom pkg-config tool and has similar options (like -cflags, -cxxflags, -libs). Unfortunately, this means they do not use pkg-config at all (and they are not planning to, as I searched through the discussion about it). While I will probably find a workaround for this project, it would be nice to have wx-config support in Meson' s dependency module.

**Comment by jpakkane** [comment]
Yes, this seems useful. I'll look into this within a few days, hopefully.

**Comment by Phitherek** [comment]
Works flawlessly on Linux, on Windows I have problems, but firstly it has non-native wx-config and secondly it can be my and/or Windows fault, so I am not going to reopen this issue. Thank you for this @jpakkane, it really simplified my meson.build for this particular project.

**Comment by fzwoch** [comment]
I have issues on Windows too. In particular I try using MSYS2 shell for the MinGW x86_64 target. A native wxwidget package is available from MSYS2.

```
$ meson.py build
The Meson build system
Version: 0.38.1
Source dir: C:/msys64/home/fzwoc/code/test
Build dir: C:/msys64/home/fzwoc/code/test/build
Build type: native build
Project name: VisionPlay
Native cpp compiler: c++ (gcc 6.3.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found wx-config: NO
Neither wx-config-3.0 nor wx-config found; can't detect dependency

Meson encountered an error in file meson.build, line 3, column 0:
Dependency "wxwidgets" not found
```

```
$ which wx-config
/mingw64/bin/wx-config
$ wx-config --version
3.0.2
```

**Comment by nirbheek** [comment]
@fzwoch please file a new bug for that :)
