### ISSUE TITLE
Link error when using boost_thread

### ISSUE THREAD

**Issue by axxel** [jpakkane/meson#31]
I found a problem with the boost framework implementation. I suggest to change the boost linkexe test-case to exhibit the problem:
```c++
#include<boost/thread.hpp>

boost::recursive_mutex mut;

struct callable {
    void operator()() {
        boost::recursive_mutex::scoped_lock l(mut);
    };
};

int main(int argc, char **argv) {
    callable x;
    boost::thread thr(x);
    thr.join();
    return 0;
}
```
With this code I get an ```undefined reference to symbol 'pthread_mutexattr_settype'``` link error. This may be resolved by appending the ```-lpthread``` linker flag. cmake seems to do this automatically, presumably when linking with the boost_thread library. So that is what I suggest (for not knowing any better option).

**Comment by jpakkane** [comment]
The whole threading issue with compilers and systems is complicated (as one would expect). I really want to have a good solution for the general case but unfortunately don't have all the knowledge, especially on the Windows side of things.

In the mean time I'll do a fix for this particular case soon, because it really should work automatically.

**Comment by Xenopathic** [comment]
Perhaps it doesn't make sense to use the `dependency()` construct to define a testing framework? It might be better to have an additional parameter to the `test()` construct, a `framework` parameter? Then that parameter would bring in the required dependencies, which may be more than one (like here: Boost testing framework requires `unit_test_framework`, `system` and `pthreads`).

IMHO it makes sense for `dependency()` to require explicit declaration of all libraries required - it shouldn't do automatic dependency evaluation.

**Comment by axxel** [comment]
I agree with Jussi: this should work automatically. Especially since the dependency on pthreads is an implementation detail (and platform specific). If there were proper (upstream) pkg-config support for boost, it would also list -lpthreads in its --libs list (at least, I would expect it to. see also https://svn.boost.org/trac/boost/ticket/1094)

If someone wonders why an explicit -pthread is necessary when using the boost::mutex but not when using boost::thread, even though the implementation of the latter is also clearly dependent on libpthread. Here is some background: https://wiki.debian.org/ToolChain/DSOLinking.

Also: this issue has nothing to do with 'testing'. I simply modified the existing test to have a quick and easy example to reproduce the issue. Having said that, there might be other boost libs than boost_thread that have #include-based dependencies on external libs.

**Comment by axxel** [comment]
The boost test case now works for me, but my own project does not configure anymore. I get the following python exception:
````
Traceback (most recent call last):
  File "/home/axel/bin/meson.py", line 184, in <module>
    app.generate()
  File "/home/axel/bin/meson.py", line 147, in generate
    g.generate()
  File "/home/axel/contrib/meson.git/ninjabackend.py", line 132, in generate
    [self.generate_target(t, outfile) for t in self.build.get_targets().values()]
  File "/home/axel/contrib/meson.git/ninjabackend.py", line 132, in <listcomp>
    [self.generate_target(t, outfile) for t in self.build.get_targets().values()]
  File "/home/axel/contrib/meson.git/ninjabackend.py", line 263, in generate_target
    elem = self.generate_link(target, outfile, outname, sorted(obj_list), linker, pch_objects)
  File "/home/axel/contrib/meson.git/ninjabackend.py", line 1293, in generate_link
    commands += linker.thread_link_flags()
AttributeError: 'ArLinker' object has no attribute 'thread_link_flags'
````

**Comment by jpakkane** [comment]
I pushed a fix.
