### ISSUE TITLE
several install_subdir() issues

### ISSUE THREAD

**Issue by axxel** [jpakkane/meson#32]
I'd like to be able to do the following: have a var/www subdirectory with a bunch of files and subsubdirectories in my sources tree and install that either (A) on my system, i.e. copy the contents of var/www into /var/www (with the prefix set to /usr for all the standard suff); or install it (B) into a $(DESTDIR)/var/www directory for having dpkg-build take care of it later.

My problem is now that (as far as can tell):
 * (A) is not possible, since my subdir will allways be prefixed in ninjabackend.py:476
 * (B) is not possible, since DESTDIR is not used for subdirs in meson_install.py:35ff
 * even if (A) worked, the install target would remove everything from /var/www which would be 'not cool'

I could start hacking and fix all 3 issues (for the ninja nackend) but wanted to check first whether I've overlooked something obvious again.

**Comment by jpakkane** [comment]
Yes, installing stuff to somewhere non-prefixed is a hassle at the moment and really needs to be sorted out. I hope to look into this soon, but this weekend I'm at Fosdem so time is limited. :)

In the mean time if you just want to get stuff done, I recommend that you write a custom install script with which you can do whatever you want. Docs [here](https://github.com/jpakkane/meson/wiki/Reference%20manual) under the methods of Meson object.
