### ISSUE TITLE
Data function must have at least one argument: the subdirectory.

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#36]
meson.build:
```
project('proj', 'c')
subdir('data')
```

data/meson.build:
```
install_data(sources : 'durka.manager',
             install_dir : 'share/telepathy/managers')
install_data(sources : 'org.freedesktop.Telepathy.ConnectionManager.durka.service',
             install_dir : 'share/dbus-1/services')
```

`meson ..`:
```
Meson encountered an error in file data/meson.build, line 1, column 0:
Data function must have at least one argument: the subdirectory.
```

**Comment by jpakkane** [comment]
Is this with git trunk or release version? In Git this should work (test case 12), this has changed since the last release AFAICR.

**Comment by ignatenkobrain** [comment]
I have latest released version (0.22.0)

**Comment by jpakkane** [comment]
In the old version you need to do the following:

install_data('telepathy/managers', sources : 'durka.manager')

As you can tell this is very confusing and backwards, which is why this was changed to the more usable new syntax.

**Comment by ignatenkobrain** [comment]
ah. I see.

https://github.com/jpakkane/meson/commit/99bb73e6c96655fe335dbeca6ae2f8dc7986d213

I'll backport this commit to fedora package
