### ISSUE TITLE
install_data() after configure_file()

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#38]
```
conf_data = configuration_data()
tp_durka_exec = prefix + '/' + libexecdir + '/telepathy-durka'
conf_data.set('TELEPATHY_DURKA_EXEC', tp_durka_exec)
configure_file(input : 'org.freedesktop.Telepathy.ConnectionManager.durka.service.in',
               output : 'org.freedesktop.Telepathy.ConnectionManager.durka.service',
               configuration : conf_data)

install_data(sources : 'org.freedesktop.Telepathy.ConnectionManager.durka.service',
             install_dir : dbusservicesdir)
```

I have this meson.build in one of subdirs. I'm getting error on install step.
```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tito/rpmbuild-telepathy-durkaIFCQz_/BUILD/telepathy-durka-git-0.15f464e/data/org.freedesktop.Telepathy.ConnectionManager.durka.service'
```

I've tried to do something like `service = configure_file(...blah...)` and use it to install, but looks like `configure_file()` doesn't return anything.

**Comment by jpakkane** [comment]
This is not in 0.22 as it was added just recently with this commit: 87ea869f0229af1448dce0a49718eebe47492018

In older versions the only solution is to have your custom install script, so something like this:

    #/bin/sh
    cp ${MESON_BUILD_ROOT}/foo/bar.dat ${DESTDIR}${MESON_INSTALL_PREFIX}/subdir

**Comment by ignatenkobrain** [comment]
ah, it's again about documentation. update reference manual, please.

**Comment by jpakkane** [comment]
Updated. Thanks for noticing.
