### ISSUE TITLE
[RFE] add function to get variables from pkgconfig files

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#46]
for example, gobject-introspection-1.0.pc:
```
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
bindir=/usr/bin
datarootdir=${prefix}/share
datadir=/usr/share
includedir=/usr/include

g_ir_scanner=${bindir}/g-ir-scanner
g_ir_compiler=${bindir}/g-ir-compiler
g_ir_generate=${bindir}/g-ir-generate
gidatadir=${datadir}/gobject-introspection-1.0
girdir=${datadir}/gir-1.0
typelibdir=${libdir}/girepository-1.0

Cflags: -I${includedir}/gobject-introspection-1.0 
Requires: glib-2.0 gobject-2.0
Requires.private: gmodule-2.0 libffi
Libs: -L${libdir} -lgirepository-1.0
Libs.private: 

Name: gobject-introspection
Description: GObject Introspection
Version: 1.43.3
```

And if I want to properly install gir packages I need to know typelibdir, girdir. I think other pc files can contain such things.

**Comment by jpakkane** [comment]
This does not seem to require its own function, since you can do it with a one-liner:

    value = run_command('pkg-config', '--variable', 'varname', 'modname').strip()

**Comment by ignatenkobrain** [comment]
makes sense. thanks!

**Comment by jpakkane** [comment]
Argh, meant this of course:

    value = run_command('pkg-config', '--variable', 'varname', 'modname').stdout().strip()
