### ISSUE TITLE
[RFC] install to python dir

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#51]
Why we're installing meson to `/usr/share/meson` instead of `/usr/lib/python3.4/meson`?

Main problem is that symlinks from `/usr/bin/` to `/usr/share/meson/` is not good.

Second problem is that I can't use meson internals (e.g. `introspect`) from other python progs.

**Comment by jpakkane** [comment]
Your last sentence is exactly the reason. Meson does not provide a stable Python API and does not plan to, either. It is installed into share to prevent anyone from importing it. Meson provides only one interface for all programs (IDEs etc) and that is the command line programs. 

What sort of problems do the symlinks cause? At least on Debian they don't cause any issues.

**Comment by jpakkane** [comment]
Note that introspect should have been installed as an executable in /usr/bin. I had just forgotten to do that. This is now fixed.

**Comment by ignatenkobrain** [comment]
@jpakkane cool! thanks! so let's close this.
