### ISSUE TITLE
won't install rpm macros

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#56]
```
Installing RPM macros to /home/brain/rpmbuild/BUILDROOT/meson-0.22.0-7.20150321gita5f30e7.fc23.x86_64/usr/lib/rpm/macros.d.
Traceback (most recent call last):
  File "./install_meson.py", line 112, in <module>
    shutil.copyfile('macros.meson', outfilename)
  File "/usr/lib64/python3.4/shutil.py", line 108, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/brain/rpmbuild/BUILDROOT/meson-0.22.0-7.20150321gita5f30e7.fc23.x86_64/usr/lib/rpm/macros.d/macros.meson'
```
We need to do mkdir I think and have install option in `OptionParser` instead of check if path exists

**Comment by jpakkane** [comment]
Fixed the directory creation.

I would prefer it if there was a reliable way to detect whether you should install the rpm macros or not so because less configuration options is always better. If there is no reliable way, though, then adding an option is ok.

**Comment by ignatenkobrain** [comment]
I think we need to check if `/usr/bin/rpm` is exists.

**Comment by ignatenkobrain** [comment]
@jpakkane checking for `/usr/bin/rpm` works for me in packaging `meson` in Fedora. I think it will also work in other cases.

**Comment by ignatenkobrain** [comment]
@jpakkane #57
