### ISSUE TITLE
[RFE] ac_config_headers

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#64]
https://www.gnu.org/software/autoconf/manual/autoconf-2.65/html_node/Configuration-Headers.html

As far as I know it's header-styled (`#define VAR VAL`) of all setted up variables (in autotools using `AC_SUBST()`) + some internal variables like `PACKAGE_NAME`, `PACKAGE_STRING`, `PACKAGE_VERSION` and some more.

I think we can inspect all `build.ConfigurationData` classes and create this file.

**Comment by jpakkane** [comment]
Meson specifically does *not* take set variables by default when doing a configuration file. The reason for this is that it becomes a debugging nightmare especially with subprojects. Any variable that you want expanded in a configuration file must be put in the configuration data object explicitly.

**Comment by ignatenkobrain** [comment]
@jpakkane ok.
