### ISSUE TITLE
[RFE] -export-symbols-regex from libtool

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#65]
Many libs using `-export-symbol` or `-export-symbools-regex` when compiling shared libs and having analogue for this option in `build.SharedLibrary` would be great.

**Comment by jpakkane** [comment]
You can already do this, see test linuxlike/3 linker script.

**Comment by ignatenkobrain** [comment]
I can't use regex there (at least I couldn't find example) and there a bit more info to specify like version of lib (not sure about this)

**Comment by jpakkane** [comment]
You can specify regexes (or globs at least) in the visibility map. See for example:

https://bazaar.launchpad.net/~mediascanner-team/mediascanner2/trunk/view/head:/src/mediascanner/mediascanner-2.0.map

**Comment by ignatenkobrain** [comment]
Cool. Can you add note about this in doc?

**Comment by jpakkane** [comment]
It is now in the FAQ.
