### ISSUE TITLE
modules/gnome: parametrize includes for g-ir-scanner

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#69]
https://github.com/jpakkane/meson/blob/master/modules/gnome.py#L61

there can be not only `GObject-2.0`. Most of introspected libs contains much more includes.

**Comment by jpakkane** [comment]
That is true but that is the minimum that every gir project requires. We should not be adding unnecessary dependencies to users' projects. If there is need to add more arguments to gir-scanner's command line then we need to add a keyword argument for it.

**Comment by ignatenkobrain** [comment]
@jpakkane Done in #72
