### ISSUE TITLE
configure_file() & dependencies

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#78]
my testcase:
```
asversion = configure_file(
  input : 'as-version.h.in',
  output : 'as-version.h',
  configuration : conf)
sources = [
  'src.c',
  asversion]
```

I'm getting error if I will specify manually this name of file: `Tried to add non-existing source as-version.h.`

**Comment by jpakkane** [comment]
You don't need to add the file to a target (and indeed should not). It is generated before build starts so it's always there. The dependency system will pick it up automatically.

The only reason to do this would be to have it show up in a list of files in an IDE. Then it should go into extra_files, though it will probably give you the same error. We'll get that fixed at some point.

**Comment by ignatenkobrain** [comment]
@jpakkane I need to specify this file to gobject-introspection. Without it I will have problems with girs.

So I think we need to implement this.

**Comment by jpakkane** [comment]
Ah, ok, that makes sense.

**Comment by jpakkane** [comment]
Fixed in trunk. Forgot to write the closing comment so closing manually.

**Comment by ignatenkobrain** [comment]
@jpakkane actually it's not fixed.
