### ISSUE TITLE
Spaces in test names makes browsing that directory hard under Linux

### ISSUE THREAD

**Issue by kirbyfan64** [jpakkane/meson#85]
I can't just do this:

```
$ cd test cases/7 mixed
```

Instead, I always have to use quotes:

```
$ cd "test cases/7 mixed"
```

or globs:

```
$ cd test*/7*ed
```

which can be slightly confusing. Can't the tests just use dashes in the names?

**Comment by jpakkane** [comment]
All tests are in directories with spaces in them on purpose. This forces the implementation to do quoting right from the start (it has already uncovered a bunch of bugs). For cd'ing into them just use tab completion. It takes care of inserting autoquoted spaces.

**Comment by kirbyfan64** [comment]
@jpakkane I guess that makes sense.

**Comment by ignatenkobrain** [comment]
you want to use `cd test\ cases/7\ mixed`
