### ISSUE TITLE
configure_file() vs shared_library() - Tried to add non-existing source

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#88]
```
Meson encountered an error in file libappstream-glib/meson.build, line 81, column 0:
Tried to add non-existing source /home/brain/git/upstream/appstream-glib/build/libappstream-glib/as-version.h.
```
```
asglib = shared_library(
  'appstream-glib', sources,
  soversion : lt_current,
  version : lt_version,
  dependencies : deps,
  include_directories : include_directories('@0@/..'.format(meson.current_build_dir())),
  link_args : ['-Wl,--no-undefined', vflag],
  link_depends : mapfile,
  install : true)
```
it's fail here in `sources`, because it's array with `asversion`.

**Comment by jpakkane** [comment]
The simple solution is to not put headers in sources. This is the recommended approach. Meson will ignore all headers as it gets all dependency info from compiler invocations. Headers can be put in <tt>extra_files</tt> so they show up in IDEs that group files by target.

It should not fail, though. I'll try to get this fixed at some point.

**Comment by ignatenkobrain** [comment]
with `extra_files` it also doesn't work.
```
Tried to add non-existing extra file /home/brain/git/upstream/appstream-glib/build/libappstream-glib/as-version.h.
```

**Comment by jpakkane** [comment]
Yep. The solution for now is to leave it out of the library command altogether. I'll try to get this fixed before the next release. In the mean time you might want to do something like this:

    lib_headers = [
     'foo.h',
    # Commented out until Meson bug #88 is fixed
    # asversion
    'bar.h',
    ]
