### ISSUE TITLE
Autotools slide

### ISSUE THREAD

**Issue by techtonik** [jpakkane/meson#90]
I am watching the Meson presentation at https://www.youtube.com/watch?v=KPi0AuVpxLI so far so good. But is there a slide about autotools available somewhere? It is unreadable on YouTube, and it would be interesting to see if I can modify it to show different build systems.

**Comment by jpakkane** [comment]
The full slide set is available on LCA's web page:

http://linux.conf.au/slides/140/meson-lca2015.pdf

**Comment by techtonik** [comment]
Thanks. Apparently, it is not linked from the talk page. http://lca2015.linux.org.au/schedule/30101/view_talk

**Comment by amitdo** [comment]
> http://linux.conf.au/slides/140/meson-lca2015.pdf

@jpakkane
This link is broken.

**Comment by amitdo** [comment]
https://web.archive.org/web/20150310192021/http://linux.conf.au/slides/140/meson-lca2015.pdf
