### ISSUE TITLE
Qt5 module: qresource rebuild on file changes

### ISSUE THREAD

**Issue by jroivas** [jpakkane/meson#97]
I have small Qt5 app which utilizes qresource (qrc) file. On that qresouce file I store [QML](http://en.wikipedia.org/wiki/QML) files. I edit those QML files regularly, and thus new resource file needs to be compiled on every edit. However meson does not track files listed in qrc, and thus does not run rcc.

Example test.qrc:

    <!DOCTYPE RCC>
    <RCC version="1.0">
    <qresource prefix="/">
        <file>test.qml</file>
    </qresource>
    </RCC>

Example meson.build (relevant parts):

    test_qt = executable('test_qt',               
        sources : [
            'main.cpp',
            qt5.preprocess(qresources : 'test.qrc')
        ], dependencies : qt5dep)

The problem: changes on test.qml does not trigger rcc build for test.qrc.

From ninja point of view it's just simple list of extra dependencies, and manually adding those to build.ninja gets proper result. But I'm missing way to define them in meson (automatic or manual).

**Comment by jpakkane** [comment]
The real fix for this is this upstream Qt bug: https://bugreports.qt.io/browse/QTBUG-45460

You can specify extra dependencies like this on toplevel targets but not generator targets. I'll need to get that fixed at some point.

In the mean time you can work around this bu building the rrc file yourself with custom_target and specifying the list of files to depend on with the depends keyword argument.

**Comment by jroivas** [comment]
Thanks, will create custom_target, and see if this gets fixed in upstream.

**Comment by jpakkane** [comment]
Trunk now has this + parsing of the qrc file to do the autodetection so you don't have to. It's not 100% reliable but the best we can do with reasonable effort. Doing it properly requires the upstream fix mentioned above.

**Comment by tracernz** [comment]
This is broken on 0.42.0 with Python 3.6.2 as the Qt5 module passes mesonlib.File objects to os.path.join in a number of places. Patch in #2315.

Anyhow... I'm enquiring if the --list argument to Qt's rcc is sufficient? Not sure if it was added after you filed the Qt bug or not. It outputs the dependencies one per line. I was able to seemingly get it to work with some naieve hacking (would want more error checking before submitting the patch properly, and check which version of rcc introduced --list, and perhaps a fallback to the existing xml parsing code):
```diff
diff --git a/mesonbuild/modules/qt5.py b/mesonbuild/modules/qt5.py
index 6194a237..3a534694 100644
--- a/mesonbuild/modules/qt5.py
+++ b/mesonbuild/modules/qt5.py
@@ -87,21 +87,13 @@ class Qt5Module(ExtensionModule):
         self.tools_detected = True
 
     def parse_qrc(self, state, fname):
-        abspath = os.path.join(state.environment.source_dir, state.subdir, fname)
-        relative_part = os.path.split(fname)[0]
-        try:
-            tree = ET.parse(abspath)
-            root = tree.getroot()
-            result = []
-            for child in root[0]:
-                if child.tag != 'file':
-                    mlog.warning("malformed rcc file: ", os.path.join(state.subdir, fname))
-                    break
-                else:
-                    result.append(os.path.join(state.subdir, relative_part, child.text))
-            return result
-        except Exception:
-            return []
+        abspath = os.path.join(state.environment.source_dir, state.subdir, fname.relative_name())
+
+        stdout, stderr = Popen_safe(self.rcc.get_command() + ['--list', abspath])[1:3]
+        stdout = stdout.strip()
+        stderr = stderr.strip()
+
+        return stdout.splitlines()
 
     @permittedKwargs({'moc_headers', 'moc_sources', 'ui_files', 'qresources', 'method'})
     def preprocess(self, state, args, kwargs):
@@ -136,7 +128,7 @@ class Qt5Module(ExtensionModule):
             if len(args) > 0:
                 name = args[0]
             else:
-                basename = os.path.split(rcc_files[0])[1]
+                basename = os.path.split(rcc_files[0].relative_name())[1]
                 name = 'qt5-' + basename.replace('.', '_')
             rcc_kwargs = {'input': rcc_files,
                           'output': name + '.cpp',

```

**Comment by ePirat** [comment]
@jpakkane Ping for the above ^

I will try to add tests to my upstream fix that adds "proper" dependency file generation so that maybe it can make it into Qt 5.14 or something.

**Comment by jpakkane** [comment]
I _think_ `--list` should work if it gives either absolute paths or paths relative to current working directory. Based on a quick check it does the latter. The only real way is to try it out and write a test that does something like:

- build the project
- change in input resource file
- rebuild
- check that the resource is the new one and not the old one
